### ISSUE TITLE
The results of KDD 2022 have been released

### ISSUE THREAD

**Issue by youngfish42** [innovation-cat/Awesome-Federated-Machine-Learning#14]
KDD 2022([Research Track](https://kdd.org/kdd2022/paperRT.html), [Applied Data Science track](https://kdd.org/kdd2022/paperADS.html))

I have compiled[ the information for the KDD 2022](https://github.com/youngfish42/Awesome-Federated-Learning-on-Graph-and-Tabular-Data/#fl-in-top-dm-conferences) paper and look forward to your reference.

![图片](https://user-images.githubusercontent.com/38998412/180168306-468cc05c-bc5e-41bd-8b11-078646ab4324.png)

**Comment by coasxu** [comment]
👍
